CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) UNIQUE NOT NULL,
  description VARCHAR(255) NOT NULL,
  time_limit INTEGER NOT NULL,
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  sprints INTEGER NOT NULL
);